version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - '${HOST_APP_PORT:-80}:80'
    volumes:
      - .:/var/www/html:delegated
    depends_on:
      - php
    networks:
      - sail
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${HOST_PHP_PORT:-9000}:9000'
    environment:
      XDEBUG: '${PHP_DEBUG:-false}'
      PHP_IDE_CONFIG: "serverName=phpstorm-server"
      REMOTE_HOST: "${PHP_REMOTE_HOST:-host.docker.internal}"
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    ports:
      - '${HOST_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gts_prod
      MYSQL_USER: root
    volumes:
      - 'sail-mariadb:/var/lib/mysql'
      - ./docker/db/init:/docker-entrypoint-initdb.d
    networks:
      - sail

networks:
  sail:
    driver: bridge
volumes:
  sail-mariadb:
    driver: local
