<?php

namespace App\Admin\Models\ServiceProvider;

use App\Admin\Models\Reference\City;
use App\Admin\Models\Reference\TransportCar;
use Custom\Framework\Database\Eloquent\HasQuicksearch;
use Custom\Framework\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Provider extends Model
{
    use HasQuicksearch;

    protected array $quicksearch = ['id', 'name%'];

    protected $table = 'service_providers';

    protected $fillable = [
        'name',

        'cities',
        'cars'
    ];

    private array $savingCities;
    private array $savingCars;

    public static function booted()
    {
        static::saved(function ($model) {
            if (isset($model->savingCities)) {
                $model->cities()->sync($model->savingCities);
                unset($model->savingCities);
            }
            if (isset($model->savingCars)) {
                $model->cars()->sync($model->savingCars);
                unset($model->savingCars);
            }
        });
        static::addGlobalScope('default', function (Builder $builder) {
            $builder->orderBy('name');
        });
    }

    public function getRouteKey()
    {
        return parent::getRouteKey(); // TODO: Change the autogenerated stub
    }

    public function cities(): BelongsToMany
    {
        return $this->belongsToMany(City::class, 'service_provider_cities', 'provider_id', 'city_id');
    }

    public function cars(): BelongsToMany
    {
        return $this->belongsToMany(TransportCar::class, 'service_provider_cars', 'provider_id', 'car_id');
    }

    public function getCitiesAttribute(): array
    {
        return $this->cities()->pluck('id')->toArray();
    }

    public function setCitiesAttribute(array $cities): void
    {
        $this->savingCities = $cities;
    }

    public function getCarsAttribute(): array
    {
        return $this->cars()->pluck('id')->toArray();
    }

    public function setCarsAttribute(array $cars): void
    {
        $this->savingCars = $cars;
    }

    public function getForeignKey()
    {
        return 'provider_id';
    }

    public function contacts(): HasMany
    {
        return $this->hasMany(Contact::class);
    }

    public function __toString()
    {
        return (string)$this->name;
    }
}
